# Generated by Django 6.1.1 on 2026-10-04 00:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadzen_accounts', '0002_accountprofile_tour_completed_at_employeeinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPClient',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('redirect_uris', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCPConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=1000)),
                ('scopes', models.JSONField(default=list)),
                ('password_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadzen_accounts.mcpclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCPAuthorizationRequest',
            fields=[
                ('request_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('redirect_uri', models.CharField(max_length=1000)),
                ('resource', models.CharField(max_length=1000)),
                ('scopes', models.JSONField(default=list)),
                ('code_challenge', models.CharField(max_length=43)),
                ('state', models.CharField(blank=True, default='', max_length=2000)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('code_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadzen_accounts.mcpclient')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leadzen_accounts.mcpconnection')),
            ],
        ),
        migrations.CreateModel(
            name='MCPAccessToken',
            fields=[
                ('token_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadzen_accounts.mcpconnection')),
            ],
        ),
        migrations.CreateModel(
            name='MCPRefreshToken',
            fields=[
                ('token_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadzen_accounts.mcpconnection')),
            ],
        ),
    ]
