# Generated by Django 6.1 on 2026-10-01.

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("leadzen_config", "0002_rename_operator_country_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(default="send", max_length=32)),
                ("requested_count", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("pid", models.PositiveIntegerField(blank=True, null=True)),
                ("output", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
