# Generated by Django 6.1.1 on 2026-10-01 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadzen_config', '0004_runtimesettings'),
        ('outsend_leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('category', models.CharField(default='outreach', max_length=24)),
                ('steps', models.JSONField(default=list)),
                ('from_address', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='outreachjob',
            name='campaign_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runtimesettings',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runtimesettings',
            name='mail_api_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='runtimesettings',
            name='mail_transport',
            field=models.CharField(default='smtp', max_length=24),
        ),
        migrations.AddField(
            model_name='runtimesettings',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.CreateModel(
            name='ContactPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opted_in', models.BooleanField(default=False)),
                ('consent_note', models.CharField(blank=True, default='', max_length=500)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='outsend_leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_step', models.PositiveSmallIntegerField(default=0)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('message_id', models.CharField(blank=True, default='', max_length=320)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsend_leads.deal')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='leadzen_config.emailcampaign')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'deal'), name='campaign_deal_unique')],
            },
        ),
    ]
