# Generated by Django 6.1.1 on 2026-10-02 03:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadzen_config', '0005_emailcampaign_outreachjob_campaign_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(default='New conversation', max_length=100)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField(default='')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leadzen_config.chatthread')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.PositiveIntegerField(db_index=True)),
                ('request_id', models.UUIDField(unique=True)),
                ('status', models.CharField(default='queued', max_length=24)),
                ('steps', models.PositiveSmallIntegerField(default=0)),
                ('credits_reserved', models.PositiveSmallIntegerField(default=0)),
                ('emails_reserved', models.PositiveSmallIntegerField(default=0)),
                ('pending', models.JSONField(default=dict)),
                ('approval_expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='leadzen_config.chatthread')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running', 'awaiting_approval'])), fields=('actor_id',), name='one_active_chat_per_actor')],
            },
        ),
    ]
