# Generated by Django 6.1.1 on 2026-10-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadzen_config', '0006_chatthread_chatmessage_chatrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrun',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatrun',
            name='model_requests',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
