# Generated by Django 6.1.1 on 2026-10-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadzen_config', '0013_campaign_followup_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceContext',
            fields=[
                ('stream_token', models.UUIDField(blank=True, null=True)),
                ('stream_expires_at', models.DateTimeField(blank=True, null=True)),
                ('actor_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('references', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatthread',
            name='context',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reviewedemail',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
