# Generated by Django 6.1.1 on 2026-10-03 20:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadzen_config', '0015_chatthread_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrecipient',
            name='authorization_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='personal_steps',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='AutopilotPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('scope', models.JSONField(default=dict)),
                ('setup_hash', models.CharField(max_length=64)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('disabled_at', models.DateTimeField(null=True)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('issue', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('actor_id',), name='one_enabled_autopilot')],
            },
        ),
        migrations.CreateModel(
            name='AutopilotRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.PositiveIntegerField()),
                ('workday', models.DateField()),
                ('phase', models.CharField(default='scheduled', max_length=24)),
                ('checkpoint', models.JSONField(default=dict)),
                ('model_requests', models.PositiveIntegerField(default=0)),
                ('email_credits', models.PositiveIntegerField(default=0)),
                ('issue', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline_at', models.DateTimeField(null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='leadzen_config.autopilotpolicy')),
            ],
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='autopilot_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='leadzen_config.autopilotrun'),
        ),
        migrations.AddConstraint(
            model_name='autopilotrun',
            constraint=models.UniqueConstraint(fields=('actor_id', 'workday'), name='one_autopilot_workday'),
        ),
    ]
