import { test, expect, login, noHorizontalOverflow, contrast } from "./fixture";

test("trusted HTTPS renders, hydrates, sets private security headers and preserves keyboard focus", async ({ page, context, fixture }) => {
  const response = await page.goto("/login");
  const headers = response!.headers();
  expect(headers["content-security-policy"]).toMatch(/script-src[^;]*'nonce-[^']+'[^;]*'strict-dynamic'/);
  expect(headers["content-security-policy"]).toContain("frame-ancestors 'none'");
  expect(headers["cache-control"]).toContain("private");
  expect(headers["cache-control"]).toContain("no-store");
  expect(headers["cache-control"]).toContain("no-transform");
  expect(headers["strict-transport-security"]).toContain("max-age=31536000");
  expect(headers["x-content-type-options"]).toBe("nosniff");
  expect(headers["referrer-policy"]).toBe("no-referrer");
  await expect(page.getByRole("heading", { name: "Sign in to LeadZen" })).toBeVisible();
  await page.keyboard.press("Tab");
  await expect(page.getByLabel("Work email")).toBeFocused();
  expect(await page.getByLabel("Work email").evaluate(element => {
    const style = getComputedStyle(element);
    return style.outlineStyle !== "none" || style.boxShadow !== "none";
  })).toBe(true);
  await contrast(page, "button[type=submit]");
  await noHorizontalOverflow(page);
  await login(page, fixture);
  await expect(page.getByRole("heading", { name: /Good (morning|afternoon|evening)/ })).toBeVisible();
  const session = (await context.cookies()).find(cookie => cookie.name === "leadzen_dashboard_session");
  expect(Boolean(session?.value)).toBe(true);
  expect(session).toMatchObject({ secure: true, httpOnly: true, sameSite: "Lax", path: "/" });
  await page.getByLabel("Dark mode", { exact: true }).check();
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
  await page.getByLabel("Light mode", { exact: true }).check();
  await expect(page.locator("html")).toHaveAttribute("data-theme", "light");
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
  expect((await context.cookies()).some(cookie => cookie.name === "leadzen_dashboard_session" && Boolean(cookie.value))).toBe(false);
  await page.goto("/contacts");
  await expect(page).toHaveURL(/\/login$/);
});

test("synthetic employee creates, edits and deletes contacts; another workspace cannot see them", async ({ page, fixture, expectedHTTPFailures }) => {
  await login(page, fixture);
  await page.getByRole("link", { name: "Leads", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Leads", exact: true })).toBeVisible();
  const marker = "Browser " + fixture.fixture_id.slice(0, 8);
  const email = "browser-" + fixture.fixture_id + "@preview.example";
  await page.getByRole("button", { name: "Add contact", exact: true }).click();
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("First name", { exact: true }).fill(marker);
  await page.getByLabel("Company", { exact: true }).fill("Disposable browser fixture");
  await page.getByRole("button", { name: "Save contact", exact: true }).click();
  const row = page.getByRole("row").filter({ hasText: email });
  await expect(row).toBeVisible();
  await row.getByRole("button", { name: "Edit", exact: true }).click();
  await page.getByLabel("Company", { exact: true }).fill("Edited disposable fixture");
  await page.getByRole("button", { name: "Save contact", exact: true }).click();
  await expect(row).toContainText("Edited disposable fixture");
  const detailHref = await row.locator("a[href^='/contacts/']").first().getAttribute("href");
  expect(detailHref).toMatch(/^\/contacts\/\d+$/);
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
  await login(page, fixture, "foreign");
  await page.goto("/contacts");
  await expect(page.getByRole("row").filter({ hasText: "foreign-contact@preview.example" })).toBeVisible();
  await expect(page.getByRole("row").filter({ hasText: email })).toHaveCount(0);
  // A direct URL is deliberately tested in another authenticated workspace.
  expectedHTTPFailures.add(`/api/proxy${detailHref}:404`);
  const denied = page.waitForResponse(response => new URL(response.url()).pathname === `/api/proxy${detailHref}` && response.status() === 404);
  await page.goto(detailHref!);
  await denied;
  await expect(page.getByText(marker, { exact: true })).toHaveCount(0);
  await expect(page.getByText(email, { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
  await login(page, fixture);
  await page.goto("/contacts");
  await row.getByRole("button", { name: `Delete ${marker}`, exact: true }).click();
  await page.getByRole("button", { name: "Delete contact", exact: true }).click();
  await expect(row).toHaveCount(0);
});

test("settings persist and mobile navigation/forms fit a 375px viewport", async ({ page, fixture }) => {
  await login(page, fixture);
  await page.goto("/settings");
  await page.getByRole("button", { name: "Edit Signature", exact: true }).click();
  const signature = "Synthetic browser signature " + fixture.fixture_id.slice(0, 8);
  await page.getByLabel("Email signature", { exact: true }).fill(signature);
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Settings updated.");
  await page.reload();
  await expect(page.getByText(signature, { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 375, height: 812 });
  await noHorizontalOverflow(page);
  const opener = page.getByRole("button", { name: "Open navigation", exact: true });
  await opener.click();
  await expect(page.getByRole("button", { name: "Close navigation", exact: true })).toHaveAttribute("aria-expanded", "true");
  await page.getByRole("link", { name: "Leads", exact: true }).click();
  await expect(opener).toHaveAttribute("aria-expanded", "false");
  await noHorizontalOverflow(page);
  await page.getByRole("button", { name: "Add contact", exact: true }).click();
  await expect(page.getByLabel("Email", { exact: true })).toBeVisible();
  await noHorizontalOverflow(page);
});

test("a single-use synthetic invitation creates a password and completes provider-disabled onboarding", async ({ page, fixture }) => {
  await page.goto("/setup#token=" + fixture.setup_token);
  await expect(page.getByLabel("Password (12+ characters)", { exact: true })).toBeVisible();
  await expect(page).toHaveURL(/\/setup$/);
  const password = fixture.password + "-Setup";
  await page.getByLabel("Password (12+ characters)", { exact: true }).fill(password);
  await page.getByLabel("Confirm password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Create password", exact: true }).click();
  await expect(page.getByRole("heading", { name: "You’re ready to sign in." })).toBeVisible();
  await login(page, fixture, "setup", password);
  await expect(page).toHaveURL(/\/onboarding$/);
  await expect(page.getByRole("heading", { name: /Step 1 of 6/ })).toBeFocused();
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByLabel("I’ll add or import contacts manually; set up discovery later").check();
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByLabel("Your name", { exact: true }).fill("Synthetic browser employee");
  await page.getByLabel("Your email", { exact: true }).fill("setup@preview.example");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByRole("button", { name: "Test mailbox", exact: true }).click();
  await expect(page.getByText("Synthetic local test — no external provider calls", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByLabel("Workspace name", { exact: true }).fill("Synthetic browser workspace");
  await page.getByLabel("Product name", { exact: true }).fill("Disposable fixture product");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByLabel("Industry", { exact: true }).fill("Synthetic test companies");
  await page.getByRole("group", { name: "Target roles", exact: true }).getByLabel("Founder", { exact: true }).check();
  await page.getByRole("group", { name: "Seniority", exact: true }).getByLabel("Founder", { exact: true }).check();
  await page.getByLabel("Looks good — I reviewed this target").check();
  await page.getByLabel(/I’m authorized to use this mailbox/).check();
  await page.getByRole("button", { name: "Finish setup", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Welcome to LeadZen" })).toBeVisible();
});

test("forced synthetic password change revokes the old session and requires login with the replacement", async ({ page, fixture }) => {
  await login(page, fixture, "password_change");
  await expect(page).toHaveURL(/\/password$/);
  const password = fixture.password + "-Changed";
  await page.getByLabel("Current / temporary password", { exact: true }).fill(fixture.password);
  await page.getByLabel("New password", { exact: true }).fill(password);
  await page.getByLabel("Confirm new password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Save password & sign in again", exact: true }).click();
  await expect(page).toHaveURL(/\/login\?passwordChanged=1$/);
  await page.goto("/contacts");
  await expect(page).toHaveURL(/\/login$/);
  await login(page, fixture, "password_change", password);
  await expect(page.getByRole("heading", { name: /Good (morning|afternoon|evening)/ })).toBeVisible();
});
